version: 2

sources:
  - name: ecommerce
    database: test2-407321
    schema: test_dbt
    tables:
      - name: users
        description: Tabla de usuarios en BigQuery
      - name: distribution_centers
        description: Tabla de centros de distribución en BigQuery
      - name: orders
        description: Tabla de pedidos de BigQuery
      - name: order_items
        description: Tabla de artículos de pedidos de BigQuery
      - name: products
        description: Tabla de productos de BigQuery
      - name: inventory_items
        description: Tabla de inventario de BigQuery